theme: minima
title: Ashley's Wonderful Planet
author: Ashley
email: uceixxw@ucl.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Hello! The 'Github' world, which I like so much.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
